### ISSUE TITLE
Not found: Java Home | ./myEnvironment.sh: No such file

### ISSUE THREAD

**Issue by mohamed-ouhab** [adempiere/adempiere-docker#30]
I am facing these errors:

```
eevolution          | -----------> ConfigurationData.setAppsServerType: Invalid AppsType=jetty [1]
eevolution          | ===========> ConfigurationData.test: Not found: Java Home [1]
eevolution          | 
eevolution          | ===========> ConfigurationData.test: Not found: Java Home [1]
eevolution          | 
eevolution          | Warning: One or more of the configuration test failed.
eevolution          | 
eevolution          | Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.io.File.getAbsolutePath()" because "this.m_adempiereHome" is null
eevolution          | 	at org.compiere.install.ConfigurationData.save(ConfigurationData.java:822)
eevolution          | 	at org.compiere.install.SilentSetup.<init>(SilentSetup.java:40)
eevolution          | 	at org.compiere.install.SilentSetup.main(SilentSetup.java:76)
eevolution          | ./RUN_silentsetup.sh: 8: .: cannot open ./myEnvironment.sh: No such file
eevolution          | NOTICE:  role "adempiere" does not exist, skipping
eevolution          | ./RUN_Server2.sh: 8: .: cannot open ./myEnvironment.sh: No such file
eevolution          | ./RUN_Server2.sh: 27: ../tomcat/bin/startup.sh: Permission denied
```

**Comment by swedge218** [comment]
Having the same issue.
